### PR TITLE
GatewayAPI integration

### PR DESCRIPTION
**Pull request by Kharg**
GatewayAPI integration https://gatewayapi.com/

### CODE REVIEW

**Comment by Kharg** [comment]
Hi @yurikuzn, I fixed the issues of the previous pull request.

Is it fine now?

**Comment by yurikuzn** [comment]
Seems fine. I'll look into later.

**Comment by Kharg** [comment]
Thanks, let me know if you need an api key to test :)

**Comment by yurikuzn** [comment]
Did you test the implementation? If yes, I maybe merge w/o testing from our side.

**Comment by Kharg** [comment]
Yes, I tested it. 2FA works fine, custom sender name is used correctly.
I can provide an API key if needed

**Pull request merged**
